apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app3-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app3-config
        configMap:
          name: app3-configmap
