apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app1-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app1-config
        configMap:
          name: app1-configmap
