# -*- mode: ruby -*-
# vi: set ft=ruby :

# Machine config
CONFIG = {
  'server' => {
    ip: '192.168.56.110'
  }
}

Vagrant.configure("2") do |config|
  # Common config
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"

  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "server" do |server|
    server.vm.hostname = "rsabbahS"
    server.vm.network "private_network", ip: CONFIG['server'][:ip]
  end
end
