apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app2-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app2-config
        configMap:
          name: app2-configmap
